/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (58.79%)
 * Likes:    1670
 * Dislikes: 334
 * Total Accepted:    296.2K
 * Total Submissions: 503.4K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 * Example 1:
 *
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 *
 * Example 2:
 *
 *
 * Input: s = "", t = "y"
 * Output: "y"
 *
 *
 * Example 3:
 *
 *
 * Input: s = "a", t = "aa"
 * Output: "a"
 *
 *
 * Example 4:
 *
 *
 * Input: s = "ae", t = "aea"
 * Output: "a"
 *
 *
 *
 * Constraints:
 *
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 *
 *
 */
#include "doctest/doctest.h"
// @lc code=start
class Solution {
 public:
  char findTheDifference(string s, string t) {
    char temp = 0;
    for (size_t i = 0; i < s.size(); ++i) {
      temp ^= s[i];
      temp ^= t[i];
    }

    temp ^= t.back();

    return temp;
  }
};
// @lc code=end

TEST_CASE("389.find-the-difference") {
  Solution s;
  CHECK(s.findTheDifference("abcd", "abcde") == 'e');
  CHECK(s.findTheDifference("", "y") == 'y');
  CHECK(s.findTheDifference("a", "aa") == 'a');
  CHECK(s.findTheDifference("ae", "aea") == 'a');
}